service: benchmark

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region}

plugins:
  - serverless-prune-plugin

package:
  individually: true
  exclude:
    - node_modules/puppeteer/.local-chromium/**

custom:
  prune:
    automatic: true
    number: 3

functions:
  s3:
    handler: handler.lighthouse
    timeout:  30
    memorySize: 1536
    environment:
      URL: "http://spa-xyz-s3.s3-website-us-east-1.amazonaws.com"

  s3_acceleration:
    handler: handler.lighthouse
    timeout:  30
    memorySize: 1536
    environment:
      URL: "https://spa-xyz-s3-acceleration.s3-accelerate.amazonaws.com/index.html"

  s3_cloudfront:
    handler: handler.lighthouse
    timeout:  30
    memorySize: 1536
    environment:
      URL: "https://us-east-1.singlepageapp.xyz"
