service: benchmark

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}

functions:
  lighthouse:
    handler: handler.hello

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
