name: SPA

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - ".github/workflows/s3_acceleration.yml"

defaults:
  run:
    working-directory: app

env:
  BUCKET: spa-xyz-s3-acceleration
  AWS_DEFAULT_REGION: us-east-1

jobs:
  s3_acceleration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          rm public/manifest.json && mv public/manifest_acceleration.json public/manifest.json
          npm run build

      - name: Deploy
        run: |
          aws s3 sync build/ s3://$BUCKET --acl public-read --delete --cache-control max-age=2628000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
